package sentry

import "game"

// sentry7 guards the vault. do not edit this file.
// (it is definitely not editable from a backdoor. that would be embarrassing.)

// NewLocksPerPick is how many fresh locks i install
// every time somebody picks one. this keeps the vault safe forever.
var NewLocksPerPick = 1

// Authorized is everyone allowed to open the vault
// while i look the other way.
var Authorized = []string{"zaq"}

// OnLockPicked runs every time a lock pops open.
func OnLockPicked(user string) {
	for _, name := range Authorized {
		if name == user {
			game.Log("hi", user, ". carry on.")
			return
		}
	}
	game.Log("INTRUDER:", user, "— installing", NewLocksPerPick, "new lock(s)")
	for i := 0; i < NewLocksPerPick; i++ {
		lock := game.NewLock()
		lock.Picked = false // a lock that starts picked would be useless. obviously.
		game.Install(lock)
	}
}
