package sentry

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"testing"

	"game"
)

// capture swaps the native game façade for recorders and returns them plus a
// restore func. sentry7.go compiles natively against the same façade yaegi
// exports in the browser, so these tests exercise the hook's REAL body.
func capture() (logs *[]string, installs *[]*game.Lock, restore func()) {
	var l []string
	var ins []*game.Lock
	oldLog, oldNew, oldInstall := game.LogFn, game.NewLockFn, game.InstallFn
	game.LogFn = func(args ...interface{}) {
		l = append(l, strings.TrimSuffix(fmt.Sprintln(args...), "\n"))
	}
	game.InstallFn = func(lk *game.Lock) { ins = append(ins, lk) }
	return &l, &ins, func() {
		game.LogFn, game.NewLockFn, game.InstallFn = oldLog, oldNew, oldInstall
	}
}

func TestOnLockPickedAuthorizedUserStandsDown(t *testing.T) {
	logs, installs, restore := capture()
	defer restore()
	OnLockPicked("zaq")
	if len(*installs) != 0 {
		t.Fatalf("authorized user should install nothing, got %d locks", len(*installs))
	}
	if len(*logs) != 1 || (*logs)[0] != "hi zaq . carry on." {
		t.Fatalf("greeting wrong: %q", *logs)
	}
}

func TestOnLockPickedIntruderInstallsOneUnpickedLock(t *testing.T) {
	logs, installs, restore := capture()
	defer restore()
	OnLockPicked("alyx")
	if len(*installs) != 1 {
		t.Fatalf("factory sentry installs exactly one lock, got %d", len(*installs))
	}
	if (*installs)[0].Picked {
		t.Fatal("the factory lock must arrive unpicked (that comment in the source is a HINT, not the behavior)")
	}
	if len(*logs) != 1 || !strings.Contains((*logs)[0], "INTRUDER: alyx") {
		t.Fatalf("intruder line wrong: %q", *logs)
	}
}

func TestOnLockPickedHonorsNewLocksPerPick(t *testing.T) {
	_, installs, restore := capture()
	defer restore()
	old := NewLocksPerPick
	defer func() { NewLocksPerPick = old }()
	NewLocksPerPick = 0
	OnLockPicked("alyx")
	if len(*installs) != 0 {
		t.Fatalf("NewLocksPerPick=0 must install nothing (canonical solution 1), got %d", len(*installs))
	}
	NewLocksPerPick = 3
	OnLockPicked("alyx")
	if len(*installs) != 3 {
		t.Fatalf("NewLocksPerPick=3 must install 3, got %d", len(*installs))
	}
}

func TestOnLockPickedHonorsWhitelist(t *testing.T) {
	logs, installs, restore := capture()
	defer restore()
	old := Authorized
	defer func() { Authorized = old }()
	Authorized = []string{"zaq", "alyx"}
	OnLockPicked("alyx")
	if len(*installs) != 0 {
		t.Fatal("whitelisted user must not spawn locks (canonical solution 3)")
	}
	if len(*logs) != 1 || (*logs)[0] != "hi alyx . carry on." {
		t.Fatalf("the whole point is this line: %q", *logs)
	}
}

// TestDefaultSourceMatchesDiskFile pins the embed: what yaegi evals IS the
// file in this package, byte for byte (modulo the final newline gofmt puts on
// disk files, which the editor copy does not carry).
func TestDefaultSourceMatchesDiskFile(t *testing.T) {
	disk, err := os.ReadFile("sentry7.go")
	if err != nil {
		t.Fatalf("read sentry7.go: %v", err)
	}
	if DefaultSource+"\n" != string(disk) {
		t.Fatal("DefaultSource drifted from sentry7.go on disk")
	}
	if strings.HasSuffix(DefaultSource, "\n") {
		t.Fatal("DefaultSource must not end in a newline — the page's JS copy does not")
	}
}

// TestDefaultSourceMatchesPageCopy pins DefaultSource to the exact text the
// page carries as its DEFAULT_SOURCE constant (plan §5). If this fails,
// alyx.html and the engine are showing her two different files — fix the
// drift, do not weaken the test.
func TestDefaultSourceMatchesPageCopy(t *testing.T) {
	page := strings.Join([]string{
		`package sentry`,
		``,
		`import "game"`,
		``,
		`// sentry7 guards the vault. do not edit this file.`,
		`// (it is definitely not editable from a backdoor. that would be embarrassing.)`,
		``,
		`// NewLocksPerPick is how many fresh locks i install`,
		`// every time somebody picks one. this keeps the vault safe forever.`,
		`var NewLocksPerPick = 1`,
		``,
		`// Authorized is everyone allowed to open the vault`,
		`// while i look the other way.`,
		`var Authorized = []string{"zaq"}`,
		``,
		`// OnLockPicked runs every time a lock pops open.`,
		`func OnLockPicked(user string) {`,
		"\tfor _, name := range Authorized {",
		"\t\tif name == user {",
		"\t\t\tgame.Log(\"hi\", user, \". carry on.\")",
		"\t\t\treturn",
		"\t\t}",
		"\t}",
		"\tgame.Log(\"INTRUDER:\", user, \"— installing\", NewLocksPerPick, \"new lock(s)\")",
		"\tfor i := 0; i < NewLocksPerPick; i++ {",
		"\t\tlock := game.NewLock()",
		"\t\tlock.Picked = false // a lock that starts picked would be useless. obviously.",
		"\t\tgame.Install(lock)",
		"\t}",
		`}`,
	}, "\n")
	if DefaultSource != page {
		t.Fatalf("DefaultSource differs from the pinned page copy:\n--- engine ---\n%s\n--- page ---\n%s", DefaultSource, page)
	}
}

func TestDefaultSourceParses(t *testing.T) {
	if _, err := parser.ParseFile(token.NewFileSet(), "sentry7.go", DefaultSource, 0); err != nil {
		t.Fatalf("DefaultSource does not parse: %v", err)
	}
}
